name: DFKD_Cifar100_ResNet34_ResNet18_V37_conv012_seed40
gpu_ids:  [0] #[1] #
###############################################################3
dataroot:  '../../dataset/'  #数据集地址
model: model_CFE_mSARC_base
model_files: ['model_CFE_mSARC_base_V37']

train_normalize: [[0.5071, 0.4867, 0.4408], [0.2675, 0.2565, 0.2761]]
prin_normalize:  [[0.5071, 0.4867, 0.4408], [0.2675, 0.2565, 0.2761]]

########################################################################





#######################################################################

########################################################################
save_epoch_freq: 10 #frequency of saving checkpoints at the end of epochs






start_epoch: 0 
max_epoch: 199 

############################continue train setting#########################
which_epoch:  start
continue_train:  False 



g_steps: 200
kd_steps: 2000

optimizer_G:
  lr:   [0.001] 


optimizer_S:
  lr:  [0.1]
  lr_policy:  CosineAnnealingLR




batch_size: 256 
num_workers: 4

#################################################################


#####lambda#################################
lambda_cls: 0.5 
lambda_bn_meanvar: 1    
first_bn_multiplier: 1 
lambda_mSARC_cam_mse: 1
lambda_mSARC_gradcams_mse: 1








use_gen_mixup_cutmix: True
gen_mixup_cutmix_p:  0.7
aug_typ: channel_mix


conv_idx: [0,1,2]




use_mixup_cutmix: False


use_clip_grad: False
# lambda_clip_grad: 3



distill:
  alpha: 1 
  T: 30  
  

################################################

generator:
  arc: CMIGeneratorV3
  ngf: 64
  img_size: 32
  nc: 3
  pretrained_loc: 
  init: kaiming                 # initialization [gaussian/kaiming/xavier/orthogonal]
  input_dim: 256

student_net:
  arc: ResNet18_1028 
  init: xavier               # initialization [gaussian/kaiming/xavier/orthogonal]
  # pretrained_loc:  
  # nchannel_input: 3
  num_classes: 100


teacher_net:
  arc: ResNet34_1028
  # init: xavier                 # initialization [gaussian/kaiming/xavier/orthogonal]
  pretrained_loc: 'pretrained/MosaicKD_state_dict/cifar100/cifar100_resnet34.pth'
  nchannel_input: 3
  num_classes: 100



input_dim: 256

manualSeed: 40


#   python train/train_cvpr2023.py --config scripts/DFKD_Cifar100_ResNet34_ResNet18_V37_conv012_seed40.yaml